name: Continuous integration
on: [push]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v3
      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --check-cache
      - name: Run tests
        run: yarn test
      - name: Lint
        run: yarn lint-on-ci
